### ISSUE TITLE
"java.lang.UnsatisfiedLinkError: couldn't find DSO to load" on 64-bit only environment

### ISSUE THREAD

**Issue by seventhmoon** [facebook/SoLoader#105]
I followed the [Test your app on 64-bit hardware](https://developer.android.com/games/optimize/64-bit#test-64-bit-hardware) on developer.android.com and installing APKs using ADB command `> adb install --abi arm64-v8a YOUR_APK_FILE.apk`

But some apps in the market is not working. From the log, it looks like SoLoader is not able to locate the file to load if it is a 64-bit env.

It is a known issue?

```
04-15 15:12:27.143 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: liblog.so
04-15 15:12:27.143 E AndroidRuntime:    at com.facebook.soloader.SoLoader.j(SourceFile:18)
04-15 15:12:27.143 E AndroidRuntime:    at com.facebook.soloader.DirectorySoSource.d(SourceFile:9)
04-15 15:12:27.143 E AndroidRuntime:    at com.facebook.soloader.DirectorySoSource.a(SourceFile:1)
04-15 15:12:27.143 E AndroidRuntime:    at com.facebook.soloader.SoLoader.j(SourceFile:7)
04-15 15:12:27.143 E AndroidRuntime:    at com.facebook.soloader.SoLoader.i(SourceFile:9)
04-15 15:12:27.143 E AndroidRuntime:    at com.facebook.soloader.SoLoader.h(SourceFile:1)
```

```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1017)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by simpleton** [comment]
which version did you use during the testing?

**Comment by seventhmoon** [comment]
Android 12 and Android 13.

I am not testing my own app. I am testing apps in the market to understand their 64-bit compatibility.
So I do not know which version of SoLoader they are using.

**Comment by simpleton** [comment]
can you share the full logcat log?

btw, iirc this issue should be addressed in https://github.com/facebook/SoLoader/commit/25a2d47a98d907731feaa23faa613fdc647ebc56

**Comment by seventhmoon** [comment]
For example the YouBike app (tw.com.sstc.youbike), which is the bike sharing app in Taipei City.
It is having crash like
```
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x728a55f8 self=0xb400007c9d6dfb20
  | sysTid=21105 nice=-10 cgrp=system sched=0/0 handle=0x7de23034f8
  | state=S schedstat=( 81891951 4922683 134 ) utm=5 stm=3 core=5 HZ=100
  | stack=0x7ff8741000-0x7ff8743000 stackSize=8188KB
  | held mutexes=
  at jdk.internal.misc.Unsafe.park(Native method)
  - waiting on an unknown object
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
  at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:959)
  at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:702)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
  - locked <0x0dbe9bd1> (a java.lang.Object)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:539)
  at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:103)
  at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:73)
  at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:465)
  - locked <0x02483636> (a java.lang.Object)
  at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:681)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
  - locked <0x0d07b937> (a java.lang.Object)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:539)
  at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:103)
  at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:73)
  at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:465)
  - locked <0x0e42cea4> (a java.lang.Object)
  at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:681)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
```

**Comment by lfoliveir4** [comment]
@seventhmoon [This link](https://androidrepo.com/repo/facebook-SoLoader-android-utils) details a lot about this error, but few have solutions. Did you manage to solve it?

**Comment by lfoliveir4** [comment]
> can you share the full logcat log?
> 
> btw, iirc this issue should be addressed in [25a2d47](https://github.com/facebook/SoLoader/commit/25a2d47a98d907731feaa23faa613fdc647ebc56)



> can you share the full logcat log?
> 
> btw, iirc this issue should be addressed in [25a2d47](https://github.com/facebook/SoLoader/commit/25a2d47a98d907731feaa23faa613fdc647ebc56)

@simpleton In our app we updated to 10.3 and we still have the same error. Do you recommend any configuration that can be done to solve this problem?

**Comment by lfoliveir4** [comment]
@simpleton Has this been fixed in [this commit](https://github.com/facebook/SoLoader/commit/b28033f71c2f03eda75b728402db745d20d81875)?

**Comment by simpleton** [comment]
app bundle issue had been fixed for a while

**Comment by lfoliveir4** [comment]
@simpleton I updated to version 10.4 in my app and made a hotfix. Crash records are over! Congratulations!
